/*
 * This file is part of RFrEAK. For licensing and copyright information
 * please see the file COPYING in the root directory of this
 * distribution or contact <robin.nunkesser@udo.edu>.
 * 
 * This file is a copy of the original file distributed with
 * FrEAK (http://sourceforge.net/projects/freak427/).
 */

package freak.gui.scheduleeditor;

import freak.gui.*;

/**
 * @author Oliver
 */
public class PanelRandomSeed extends ScheduleEditorPanel {

	/** Creates new JPanel */
	public PanelRandomSeed(ScheduleEditor scheduleEditor) {
		super(scheduleEditor);
		initComponents();
	}

	public static String getDescription() {
		return "Set Random Seed";
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() { //GEN-BEGIN:initComponents
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel4 = new javax.swing.JPanel();
		jButton2 = JButtonFactory.newButton();
		jButton3 = JButtonFactory.newButton();
		jButton4 = JButtonFactory.newButton();
		jPanel13 = new javax.swing.JPanel();
		jLabel31 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();

		setLayout(new java.awt.GridBagLayout());

		setBorder(new javax.swing.border.TitledBorder("Select Random Seed"));
		jPanel4.setLayout(new java.awt.GridBagLayout());

		jPanel4.setBorder(new javax.swing.border.EtchedBorder());
		jButton2.setMnemonic('f');
		jButton2.setText("From system time");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
		gridBagConstraints.weightx = 0.1;
		jPanel4.add(jButton2, gridBagConstraints);

		jButton3.setMnemonic('l');
		jButton3.setText("Load...");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 3, 5, 5);
		gridBagConstraints.weightx = 0.1;
		jPanel4.add(jButton3, gridBagConstraints);

		jButton4.setMnemonic('a');
		jButton4.setText("Save...");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
		gridBagConstraints.weightx = 0.1;
		jPanel4.add(jButton4, gridBagConstraints);

		jPanel13.setLayout(new java.awt.GridBagLayout());

		jLabel31.setText("Random Seed:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		jPanel13.add(jLabel31, gridBagConstraints);

		jTextField2.setEditable(false);
		jTextField2.setText("<system time>");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		gridBagConstraints.weightx = 1.0;
		jPanel13.add(jTextField2, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
		gridBagConstraints.weightx = 0.1;
		jPanel4.add(jPanel13, gridBagConstraints);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.weightx = 0.1;
		gridBagConstraints.weighty = 0.1;
		add(jPanel4, gridBagConstraints);

	} //GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JPanel jPanel13;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JTextField jTextField2;
	// End of variables declaration//GEN-END:variables

}
